### ISSUE TITLE
How to get the ticker prices for BTC denominated in USD?

### ISSUE THREAD

**Issue by softwareguycoder** [bchavez/Coinbase.Pro#10]
I am really new to WebSockets.  The Coinbase Pro API documentation is very sparse and hard to read for newbies such as myself.  I tried to go to the link you specified here: https://docs.pro.coinbase.com/?r=1#subscribe  but to no avail.

What I want is the realtime(-ish) ticker price of BTC as denominated in USD -- i.e., the BTC-USD exchange rate.  I make a new Subscription object in my code thus:
```
            var sub = new Subscription
            {
                ProductIds =
                {
                    "BTC-USD"
                },
                Channels =
                {
                    "ticker"
                }
            };
```
Is this not the correct way to do it?  I suspect not.  I need some help.  OK, so let's say I've subscribed it correctly.  How do I actually see the ticker prices?

Also, I am confused as just what the ```level2```, ```heartbeat```, and ```ticker``` "channels" even are.  What is a heartbeat?  What is a level2?  What is a ticker?

Thanks.

**Comment by softwareguycoder** [comment]
OK, so I am a little sheepish, I found the example at https://github.com/bchavez/Coinbase.Pro/blob/master/Source/Coinbase.Tests/IntegrationTests/WebSocketTests.cs.

I am now aware of how to successfully subscribe.  My questions remain, however, as to just what the heck are ```level2```, ```heartbeat```, and ```ticker``` channels.  The Coinbase Pro API documentation does not appear to define that nomenclature.

**Comment by bchavez** [comment]
`level2` relates to the level of detail of the order book events you receive. 

https://docs.pro.coinbase.com/?r=1#get-product-order-book
https://docs.pro.coinbase.com/?r=1#the-level2-channel

Once you have an order book, you'll probably want to keep it updated. That's the reasoning behind the socket feed, to provide data delta-diffs (changes in state) of the market's order book.

>Level | Description
>-- | --
>1 | Only the best bid and ask
>2 | Top 50 bids and asks (aggregated)
>3 | Full order book (non aggregated)

> The easiest way to keep a snapshot of the order book is to use the level2 channel. It guarantees delivery of all updates, which reduce a lot of the overhead required when consuming the full channel.
>
>When subscribing to the channel it will send a message with the type snapshot and the corresponding product_id. bids and asks are arrays of [price, size] tuples and represent the entire order book.
>
>Subsequent updates will have the type l2update. The changes property of l2updates is an array with [side, price, size] tuples. The time property of l2update is the time of the event as recorded by our trading engine. Please note that size is the updated size at that price level, not a delta. A size of "0" indicates the price level can be removed.
-----

`heartbeat` is described here:
https://docs.pro.coinbase.com/?r=1#channels

>To receive heartbeat messages for specific products once a second subscribe to the heartbeat channel. Heartbeats also include sequence numbers and last trade ids that can be used to verify no messages were missed.

>```json
>// Heartbeat message
>{
>    "type": "heartbeat",
>    "sequence": 90,
>    "last_trade_id": 20,
>    "product_id": "BTC-USD",
>    "time": "2014-11-07T08:19:28.464459Z"
>}
>```

----

`ticker` is described here: https://docs.pro.coinbase.com/?r=1#the-ticker-channel
> The ticker channel provides real-time price updates every time a match happens. It batches updates in case of cascading matches, greatly reducing bandwidth requirements.

>```json
>{
>    "type": "ticker",
>    "trade_id": 20153558,
>    "sequence": 3262786978,
>    "time": "2017-09-02T17:05:49.250000Z",
>    "product_id": "BTC-USD",
>    "price": "4388.01000000",
>    "side": "buy", // Taker side
>    "last_size": "0.03000000",
>    "best_bid": "4388",
>    "best_ask": "4388.01"
>}
>```


If you want ticker prices for BTC denominated in USD, you'll probably want the `ticker` channel to stay up to date. However, as the documentation says, you will only be notified only when a match happens. If you subscribe to the channel, and there are no matches you'll have to wait around for the next match. 

If the market is extremely quiet, and you're still waiting around for the next match to happen you can get the last traded ticker price as described here: https://docs.pro.coinbase.com/?r=1#get-product-ticker

Hope that helps.

Thanks,
Brian

**Comment by astrohart** [comment]
Found this issue and I had the same question.

Why should I care about heartbeat events?

**Comment by bchavez** [comment]
https://docs.pro.coinbase.com/?r=1#the-matches-channel

>#### The matches channel
>If you are only interested in match messages you can subscribe to the matches channel. This is useful when you’re consuming the remaining feed using the level 2 channel.
>
>**Please note that messages can be dropped from this channel. By using the heartbeat channel you can track the last trade id and fetch trades that you missed from the REST API.**

The Coinbase documentation for Pro is mostly decent. Apologies for sounding blunt, but many of the questions here can be found in the Pro documentation.

Good etiquette and strategy is to invest some time reading the Pro documentation from the beginning up to (but excluding) the FIX API. The level of experience and expectation required using Pro is higher than compared to using the standard Coinbase API.

If anyone needs more help with concepts on how the exchange works, please contact support here:
https://support.coinbase.com/customer/portal/emails/new?brand=Pro

I'm mostly here to answer C# and .NET questions as it relates to the C# library, not so much for filling in gaps in knowledge or documentation.

Thanks,
Brian

**Comment by astrohart** [comment]
Thanks for the help. It is just really hard to understand the documentation because it’s written for professional traders and I am just an amateur.  It’s so loaded with jargon and I am just not a financial person normally.  I am a PhD scientist and I am very very interested in the math of trading plus I want to see how maybe I can make some side money. 

Brian

**Comment by bchavez** [comment]
No problem. I just wanted to set expectations because working with Pro ***demands*** a certain level of understanding because ***really*** bad financial trades can happen if you're not careful.

The market is unforgiving to those who don't understand or respect it. I've witnessed people losing their bacon big time.

For those looking to use Pro, I suggest having a firm understanding of the following (in order of preference):
1. **Order Types**. Do not move on until you fully understand these order types. YouTube is a great resource here.
   * What is a market order?
   * What is a limit order?
   * What is a stop-loss order?
   * What are the differences between each order type available on an exchange?
   * Under what specific scenarios would you use each order type?
1. **Spot Price and Spread**.
   * What are bids and asks?
   * How does an exchange determine the price of an asset?
   * What is a spot price?
   * What is price spread?
   * What are open/close gaps? (good to know, however, crypto exchanges are 24/7, so might not matter much here, except in cases when the exchange goes offline for maintenance).
   * What operational modes does your exchange support? Post-only? Full-trading mode? What are the differences and how do they relate to order types?
1. **Market Depth and Slippage**.
   * What is liquidity?
   * What is market dept? How is depth shown on a chart? What is shallow depth?
   * What is price slippage?
   * Under what circumstances can price slippage occur? (very, ***very***, important)
   * What is volume?
1. **Other**; not necessary, but very good to know.
   * What is market cap?
   * What is dominance?
   * What is the difference between BTC-USD, ETH-USD and ETH-BTC? How does each one relate to the other? What is relative strength?
   * What is arbitrage? How does arbitrage affect local and global exchanges? How can arbitrage affect the overall price of an asset?

These are prerequisite concepts to understand. Of course, there's much more to learn, but once you have a good understanding of the concepts above, you should have a general idea on how to proceed in the market and how to protect yourself on the exchange.

I do empathize with you, it's a lot of jargon to wade through but hang in there. You will thank yourself 100x times later. Also, hopefully along your journey, you'll discover the beauty, elegance, and a newfound deep appreciation for how free-markets systems work. I know I did.

Hope that helps,
Brian Chavez

:cloud_with_rain: :sun_behind_rain_cloud: ***["I wanna know... have you ever seen the rain?"](https://www.youtube.com/watch?v=Gu2pVPWGYMQ)***
