### ISSUE TITLE
CancleOrderById() throw Newtonsoft.Json.JsonSerializationException

### ISSUE THREAD

**Issue by grumson** [bchavez/Coinbase.Pro#13]
Hi!

I get an error when using method Client.Orders.CancleOrderById()

Newtonsoft.Json.JsonSerializationException: 'Error converting value "ac039c99-8bf6-4484-a95b-0d50770c4376" to type 'Coinbase.Pro.Models.JsonResponse'. Path '', line 1, position 38.'

Inner Exception:
ArgumentException: Could not cast or convert from System.String to Coinbase.Pro.Models.JsonResponse.

**Comment by bchavez** [comment]
Hi @grumson,

Thanks for your issue. In order to help you more, I think you're going to need to provide more diagnostic information about your issue.

Please follow the instructions [here](https://github.com/bchavez/Coinbase/wiki/Debugging-with-Fiddler) to debug the HTTP requests between **Coinbase.Pro** and your app. When posting the diagnostic info, please hide any API keys or any other personally identifiable information.

Also, please post the associated code and any data structures that lead up to the invocation of the `.CancelOrderById()` method.

Also, please [follow the issue template](https://github.com/bchavez/Coinbase.Pro/blob/master/.github/ISSUE_TEMPLATE/03_bug_report.md) by answering the questions when creating issues. I need this important information that was ignored to help further diagnose the issue.

Please feel free to re-open the issue when you have Fiddler and other diagnostic information ready.

Thanks,
Brian
