### ISSUE TITLE
Simple API calls are refused by target machine

### ISSUE THREAD

**Issue by mikeomatic9000** [bchavez/Coinbase.Pro#35]
I must be missing something simple, but I'm unable to make even basic API calls out of the box.

### Version Information
| Software                       | Version(s) |
| --------------------------| ---------- |
| Github Version              | 4.0.1 build 172   |
| .NET Core                      | 5.0.103           |
| .NET Full Framework?    | 4.8               |
| Windows OS?                | 10.0.19041        |
| Visual Studio?               | 16.8.5            |

### What's the problem?
Unable to make basic API calls.  Consistently getting "No connection could be made because the target machine actively refused it"

### What possible solutions have you considered? 
Ensured all frameworks were up to date.  Fresh clone from github.  .secrets.txt files in place.  Attempted on multiple networks to rule out workplace firewall issues.

### Do you have sample code to show what you're trying to do?
Any of the Coinbase.Tests.IntegrationTests, for example
 can_create_and_delete_order
   Source: GeneralTests.cs line 162
   Duration: 4.5 sec

  Message: 
    Flurl.Http.FlurlHttpException : Call failed. An error occurred while sending the request: GET https://api.pro.coinbase.com/time
      ----> System.Net.Http.HttpRequestException : An error occurred while sending the request.
      ----> System.Net.WebException : Unable to connect to the remote server

Also in the example program:
Examples\Program.cs:24
Flurl.Http.FlurlHttpException: 'Call failed. No connection could be made because the target machine actively refused it: GET https://api-public.sandbox.pro.coinbase.com/products'

**Comment by bchavez** [comment]
The reason the integration tests are failing due to a network error is that the integration tests are wired up to use the Fiddler network proxy.

https://github.com/bchavez/Coinbase.Pro/blob/1e9ba1da67958f6c42976f1e37fed7977dc2e158/Source/Coinbase.Tests/IntegrationTests/IntegrationTest.cs#L31-L36

The Fiddler network proxy is used to inspect HTTP requests and responses.

You'll need to set up Fiddler described in the link below:
https://github.com/bchavez/Coinbase/wiki/Debugging-with-Fiddler

Once Fiddler is setup as exactly described in the link above; network requests should start flowing to Coinbase. The `.secrets` file looks like this:
```json
{
  "apiKey":"...",
  "apiSecret":"...",
  "apiPassphrase":"..."
}
```
I didn't really plan for anyone else to run the integration tests except for myself; so that's why it's undocumented and the test fixture is marked `[Explicit]`.

Let me know if you have any other questions.

Thanks,
Brian
