### ISSUE TITLE
Change Coinbase.Pro.Models.Fill.Size  to decimal

### ISSUE THREAD

**Issue by minskowl** [bchavez/Coinbase.Pro#37]
Hi.
Please change 
Coinbase.Pro.Models.Fill
      [JsonProperty("size")]
      public string Size { get; set; }
to 
      [JsonProperty("size")]
      public decimal Size { get; set; }

**Comment by bchavez** [comment]
Sorry, IIRC, there may be values larger or smaller than what can be supported by `decimal`; so `string` is what is typically used right now.

Unless you can find **Coinbase Pro** docs that say `Size` is an exact decimal type that we can safely convert to, then I think we can make the change; otherwise, as it currently exists, the API returns a `string`; so the library returns a `string`:

```json
[
    {
        "trade_id": 74,
        "product_id": "BTC-USD",
        "price": "10.00",
        "size": "0.01",
        ...
    }
]
```
