### ISSUE TITLE
Parsing Exponential Numbers

### ISSUE THREAD

**Issue by cduvall** [bchavez/Coinbase.Pro#4]
Some books return exponential numbers (e.g., "7e-7" for markets like "BCH-BTC") as valid values.  Instead of reading as a decimal, it can be read as a string and parsed with `decimal.Parse`

`decimal.Parse("7e-7", System.Globalization.NumberStyles.Any)`

Known Newtonsoft.Json issue: https://github.com/JamesNK/Newtonsoft.Json/issues/1711

**Comment by bchavez** [comment]
Thanks for the bug report Christian.

The issue was ultimately resolved by taking a hard dependency on the fix inside `Newtonsoft.Json` at v12.0.1.

https://www.nuget.org/packages/Coinbase.Pro/2.0.3

Thanks,  
Brian

:walking_man: :walking_woman: **[Missing Persons - Walking in L.A.](https://www.youtube.com/watch?v=R_UpLtGEWoY)**
