### ISSUE TITLE
Easier Channel Registration

### ISSUE THREAD

**Issue by granthoff1107** [bchavez/Coinbase.Pro#40]
**Feature Request:**  

Fluent Subscription builder for easier channel Registration.

Problem:

The api currently mitigates the responsibility on understanding the API spec to the end user, instead of relying on internal structures to make it easier to register.  Take this example I tried using which failed:

        protected Subscription GetDefaultSubscription()
        {
            return new Subscription
            {
                ProductIds = this.SupportedProducts.ToList(),
                Channels = this.GetDefaultChannels()
            };
        }

        private JArray GetDefaultChannels()
        {
            var channels = new JArray
            {
                "level2",
                JObject.FromObject(
                new Channel
                {
                    Name = "ticker",
                    ProductIds = this.SupportedProducts.ToList()
                }),
                JObject.FromObject(
                new Channel
                {
                    Name = "match",
                    ProductIds = this.SupportedProducts.ToList()
                })
            };
    }

Its really hard to tell here why I couldn't get the matches,  and the problem was the fact the the `match channel` should be called using the name "matches" not "match" 

**Additional notes**

I additionally did another search internal to the project for the term match, there related to obtaining matches.  Which could be used as an example.  

There are a lot of magic string's being reused in the existing library such as "heartbeat", "matches" that should have a related const file to make it easier for new users to use.    

**Solution:**

Registering for channels might be nicer if we could just do something like this

       //Normally this would be in consts file some where.
      const string BTC_USD_PRODUCT_ID = "BTC-USD";

      var subscription= SubscriptionBuilder.AddCurrencies(BTC_USD_PRODUCT_ID ).AddChannels(ChannelType.Ticker, ChannelType.Matches).Build();

**Comment by bchavez** [comment]
I agree with much of your ideas; however, the other side of the equation is maintenance.

> The api currently mitigates the responsibility on understanding the API spec to the end user

Absolutely. This is by design. It costs me a lot of time to maintain this **Coinbase.Pro** project. Every time **Coinbase** launches a new asset on the platform we'd have to add `BTC_USD_PRODUCT_ID`, `ETH_USD_PRODUCT_ID`, `XML_USD_PRODUCT_ID`, *etc.*, *etc.*, *etc.*.

**I do not want to spend my free time on OSS updating "supported" **Coinbase** Product IDs.**

I've purposely designed the **Coinbase.Pro** library so that when a new asset is traded on Coinbase; it doesn't require a full-on update of the **Coinbase.Pro** library. Developers can just begin using "XYZ-USD"-whatever and have everything just work.

The same idea similarly applies with much of the "model" types using `string`s. All this does come at a cost... to the user. As a consequence of the decision, the user bears some of the "maintenance" costs with respect to untyped fields.

The problem I'm trying to avoid is adding code that I will have to maintain later. The API documentation for **Coinbase.Pro** is continually changing and a moving target. The less hard-coded stuff I have in the library, ***the less I have to maintain.***
