### ISSUE TITLE
Unauthorized Response for all Requests

### ISSUE THREAD

**Issue by atomroflman** [bchavez/Coinbase.Pro#44]
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| NuGet Package            | 4.1.12                |
| .NET Full Framework?   | 5.0                |
| Windows OS?              | 10                  |

### What's the problem?
I get an unauthorized response for every request with a freshly generated API key.

### What possible solutions have you considered? 
Using the Sandbox environment.
Creating a new key.
Linking latest Github version.
Adding ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

### Do you have sample code to show what you're trying to do?
```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
var Configuration = config.GetSection("TradingPlatforms:Coinbase");
var cbConf = new Coinbase.Pro.Config()
{
	ApiKey = Configuration.GetValue<string>("ApiKey"),
	Secret = Configuration.GetValue<string>("ApiSecret"),
	Passphrase = Configuration.GetValue<string>("ApiPassphrase"),
	ApiUrl = "https://api-public.sandbox.pro.coinbase.com"
};
var cb = new CoinbaseProClient(cbConf);
(await cb.Orders.GetAllOrdersAsync()).Dump();

```
_(Please be complete. Include any class models necessary to run your code.)_

### What is the HTTP request JSON and response JSON?
```
Flurl.Http.FlurlHttpException: Call failed with status code 401 (Unauthorized): GET https://api-public.sandbox.pro.coinbase.com/orders?status=all
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token) in C:\projects\flurl\src\Flurl.Http\FlurlRequest.cs:line 348
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) in C:\projects\flurl\src\Flurl.Http\FlurlRequest.cs:line 195
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption) in C:\projects\flurl\src\Flurl.Http\FlurlRequest.cs:line 201
   at Coinbase.Pro.ExtensionsForCoinbaseProClient.GetPagedJsonAsync[T](IFlurlRequest request, CancellationToken cancellationToken)
   at UserQuery.Main() in C:\Users\poweleit\AppData\Local\Temp\LINQPad6\_ykyykbkq\wpwcee\LINQPadQuery:line 42

```
_(Use Fiddler to help capture this information)_

**Comment by bchavez** [comment]
Things to check for:
* Make sure your computer's time is synchronized with an NTP server; otherwise, if Coinbase's servers receive an API request with a signature timestamped outside of a 30-second window, it will reject the request. For example, if your computer is more than 30 seconds behind Coinbase's server time; Coinbase will reject the request.
  
  Otherwise, if you want to isolate yourself from any clock skew, then you can set `cbConfig.UseTimeApi = true`. However, this will effectively make the `Coinbase.Pro` client make **_two_** HTTP requests to Coinbase on every API call;
   1 - to get the current time at Coinbase and
   2 - use the current time at Coinbase to calculate the required signature for your actual intended request.
  
  Read more here: https://docs.pro.coinbase.com/#selecting-a-timestamp
  > Your timestamp must be within 30 seconds of the api service time or your request will be considered expired and rejected. We recommend using the time endpoint to query for the API server time if you believe there many be time skew between your server and the API servers.
* Use [**Fiddler**](https://github.com/bchavez/Coinbase/wiki/Debugging-with-Fiddler) to debug HTTPS requests to find more diagnostic information about why the request is failing. Check that `ApiKey`, `Secret`, and `Passphrase` are actually being populated with the intended value and ensure those values are consistent with what you see in your account API setup.
