### ISSUE TITLE
Unable to use Coinbase.Pro sandbox

### ISSUE THREAD

**Issue by doomtr666** [bchavez/Coinbase.Pro#7]
Hi,

When fetching the products using the Coinbase.Pro sandbox, I got this error:

Exception non gérée : Flurl.Http.FlurlParsingException: Response could not be deserialized to JSON: GET https://api-public.sandbox.pro.coinbase.com/products ---> Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Decimal'. Path '[0].min_market_funds', line 1, position 250. ---> System.InvalidCastException: Impossible de convertir un objet null en un type valeur.

I could be nice if the sandbox is supported as well !

Cheers,
Christophe

**Comment by bchavez** [comment]
Hi Christophe,

New version of [**Coinbase.Pro** `v2.0.5`](https://www.nuget.org/packages/Coinbase.Pro/2.0.5) is out with the fix.

Thanks for reporting the issue. :)
Brian

:walking: :sunglasses: ***["So don't delay... act now supplies are running out..."](https://www.youtube.com/watch?v=LQj--Kjn0z8)***

**Comment by doomtr666** [comment]
Thanks,

But now, I'm getting a 400 error:

Flurl.Http.FlurlHttpException: Call failed with status code 400 (Bad Request): GET https://api-public.sandbox.pro.coinbase.com/accounts

**Comment by bchavez** [comment]
Hi Christophe,

Thank you for the error report.

Could you please provide a Fiddler dump of the HTTP traffic for the accounts GET request so we can get a fix on the 400 error?

Seems a little strange because the commit d3fda5b546b783ed44ad84f8ae8d554c2ef8103d was just a nullable model type change on the deserializing end. Not sure how we can get a 400 on a simple get request. The HTTP dump of the request and resposne should clear things up.

Thanks,
Brian

**Comment by doomtr666** [comment]
Hi Brian,
It seems my sandbox API key was revoked, nothing related to your library. I get various internal server errors too, the sandbox does not seem to be very stable.
Anyway thank you for you great work !
Christophe

**Comment by crayse1** [comment]
Has the sandbox issues been resolved? I would like to test my bot using this. Thanks

**Comment by bchavez** [comment]
@crayse1, Yes, set the `Config.ApiUrl` to the sandbox API URL. Create a new issue if you have any problems.
