### ISSUE TITLE
What does Config.UseTimeApi mean?

### ISSUE THREAD

**Issue by astrohart** [bchavez/Coinbase.Pro#9]
In the ```Config``` class, there is a ```UseTimeApi``` property.  What does it do?

**Comment by bchavez** [comment]
Hi Brian,

Roughly, [a timestamp is required as part of the HMAC authentication signature][2] on each request made to Coinbase's servers. Coinbase uses the timestamp for a few reasons, but mostly, I think to make sure HTTP requests are relatively recent; thereby narrowing the window for replay attacks.

When `UseTimeApi = false` is that your own local system time is used. The problem with your local time source is that if your time is not synchronized with global NTP time servers, clock skew could be a problem when making requests to Coinbase. For example, if your computer or server's time is off by 10 or 15 minutes, Coinbase might start rejecting requests.

[1]:https://docs.pro.coinbase.com/#time
[2]:https://docs.pro.coinbase.com/#creating-a-request

When `UseTimeApi = true`, the [current time][1] from Coinbase is retrieved and is used instead of the local system time; thereby avoiding the "clock skew" problem.

Hope that helps,
Brian
